In [4]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../../../qorange'))

# Quantum Algorithm Examples

## Entanglement Circuit

In [ ]:
from qorange.circuits import *
from qorange.gates import *

circuit = QuantumCircuit()

H = Hadamard()
CNOT = CNOT()

circuit.apply_gate(H, 1)
circuit.apply_gate(CNOT, (1,2))
circuit.draw()

   ┌───┐              
───│ H │────────●─────
   └───┘        │     
                │     
────────────────○─────
                      


In [9]:
print("State Vector:")
print(circuit.state)
print("Density Matrix:")
print(circuit.density_matrix)

State Vector:
[0.70710678 0.         0.         0.70710678]
Density Matrix:
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]


In [12]:
print("Reduced Density Matrix on Qubit 1:")
print(circuit.partial_trace(keep=1))

print("Reduced Density Matrix on Qubit 2:")
print(circuit.partial_trace(keep=2))

Reduced Density Matrix on Qubit 1:
[[0.5 0.5]
 [0.5 0.5]]
Reduced Density Matrix on Qubit 2:
[[0.5 0.5]
 [0.5 0.5]]


In [16]:
print("Measure Qubit 1:")
m1 = circuit.measure_qubit_computational(1)
print(f"Probability of being in state |0>: {m1[0]}")
print(f"Probability of being in state |1>: {m1[1]}")

print("Measure Qubit 2:")
m2 = circuit.measure_qubit_computational(2)
print(f"Probability of being in state |0>: {m2[0]}")
print(f"Probability of being in state |1>: {m2[1]}")

Measure Qubit 1:
Probability of being in state |0>: 0.5
Probability of being in state |1>: 0.5
Measure Qubit 2:
Probability of being in state |0>: 0.5
Probability of being in state |1>: 0.5


## 2-Qubit Quantum Fourier Transform

## Hadamard Test

In [ ]:
from qorange.circuits import *
from qorange.gates import *

circuit = QuantumCircuit()

H = Hadamard()

P = PhaseGate(np.pi/2)

CP = ArbControlledGate(P)

circuit.apply_gate(P, 1)
circuit


## Deutsch Josza